### ISSUE TITLE
Update for Omnipay2?

### ISSUE THREAD

**Issue by realityking** [ismailasci/omnipay-sofort#5]
While I'm not currently using Omipay, I'm considering it as part of a larger refactoring. Are there any plans to update this gateway to work with Omnipay2?

**Comment by ismailasci** [comment]
Hey Rouven. Sorry for the late response.

I was planning to make the changes due to make it compatible for Omnipay 2.x. It must be done now, you can check [master](https://github.com/ismailasci/omnipay-sofort/tree/master) branch or [v2.1.0](https://github.com/ismailasci/omnipay-sofort/tree/v2.1.0) tag.

I hope it can get a place in your refactoring plans :)
